// Generated by `think types`. Do not edit this file directly.
// Re-run `think types` after changing Think agents or Wrangler bindings.
// <think-generated>
declare module "virtual:think/entry" {
  const entry: ExportedHandler<Cloudflare.Env>;
  export default entry;
  export const ThinkAgent_Studio: (typeof import("./agents/studio/agent"))["Studio"];
  export const ThinkSubAgent_Studio_Song: (typeof import("./agents/studio/agents/song/agent"))["Song"];
}
declare module "virtual:think/router" {
  export const thinkRouter: import("@cloudflare/think/server-entry").ThinkRouter;
}

declare namespace Cloudflare {
  interface Env {
    ThinkAgent_Studio: DurableObjectNamespace<
      InstanceType<(typeof import("./agents/studio/agent"))["Studio"]>
    >;
  }
}
// </think-generated>
